// vue/src/components/ERC721Checker.vue
<template>
  <div className="wrapper">
    <p className="title">Step2: Get your NFT</p>
    <input placeholder="token ID" v-model="tokenId" type="text" />
    <div v-if="onGoing" className="center">Loading...</div>
    <button v-else @click="get">get</button
    ><img v-if="base64" :src="base64" alt="hoge" className="image" />
    <p v-if="name">Name: {{ name }}</p>
    <p v-if="description">Description: {{ description }}</p>
  </div>
</template>

<script>
export default {
  name: "ERC721Checker",
  data() {
    return {
      name: "",
      description: "",
      base64: null,
      onGoing: false,
      tokenId: null,
    };
  },
  props: {
    contract: Object,
    userAddress: String,
  },
  methods: {
    get: function () {
      const submit = async () => {
        this.onGoing = true;
        try {
          console.log(this.contract, this.tokenId);
          const { data: tokenUri } = await this.contract.tokenURI(this.tokenId);
          const url = tokenUri.replace(/^ipfs:\/\//, "https://ipfs.io/ipfs/");
          const res = await fetch(url);
          const data = await res.json();
          this.base64 = data.base64;
          this.name = data.name;
          this.description = data.description;
        } catch (err) {
          console.error(err);
        } finally {
          this.onGoing = false;
        }
      };
      submit();
    },
  },
};
</script>

// react/src/components/ERC721Checker.jsx
import { useState } from "react";

export const ERC721Checker = ({ bunzz, userAddress }) => {
  const [base64, setBase64] = useState(null);
  const [tokenId, setTokenId] = useState("");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [onGoing, setOnGoing] = useState(false);

  const submit = async () => {
    setOnGoing(true);
    try {
      const contract = await bunzz.getContract("NFT (IPFS Mintable)");
      const { data: tokenUri } = await contract.tokenURI(tokenId);
      const url = tokenUri.replace(/^ipfs:\/\//, "https://ipfs.io/ipfs/");
      const res = await fetch(url);
      const data = await res.json();
      setBase64(data.base64);
      setName(data.name);
      setDescription(data.description);
    } catch (err) {
      console.error(err);
    } finally {
      setOnGoing(false);
    }
  };

  return (
    <div className="wrapper">
      <p className="title">
        Step2: Get your NFT
      </p>
      <input
        placeholder="token ID"
        value={tokenId}
        onChange={(e) => setTokenId(e.target.value)}
        type="text"
      />
      {onGoing ? (
        <div className="center">
          Loading...
        </div>
      ) : (
        <button onClick={submit}>
          get
        </button>
      )}
      {base64 ? (
          <img src={base64} alt="hoge" className="image" />
      ) : (
        <></>
      )}
      {name ? <p>Name: {name}</p> : <></>}
      {description ? <p>Description: {description}</p> : <></>}
    </div>
  );
};
